org: jkcgs
service: owo-services
plugins:
  - serverless-python-requirements
  - serverless-domain-manager
  - serverless-wsgi
provider:
  name: aws
  runtime: python3.8
  stage: default
  region: us-west-2
custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
  customDomain:
    domainName: api.owo.cl
    basePath: 's'
    stage: ${self:provider.stage}
functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'